language: php

os: linux

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --testsuite unit --verbose

notifications:
  email: false
