language: php

os: linux

php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - $HOME/.composer/cache

install: travis_retry composer install

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.2' ]; then
      PHPUNIT_FLAGS="--coverage-clover=build/logs/clover.xml"
    fi

script:
#  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --diff
  - vendor/bin/phpcs --standard=PSR12 src tests -s -p -n --parallel=4 --colors
  - mkdir -p build/logs
  - vendor/bin/phpunit --testsuite unit $PHPUNIT_FLAGS

after_success:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.2' ]; then
      travis_retry php vendor/bin/php-coveralls -v
    fi

notifications:
  email: false
