language: php

os: linux

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

cache:
  directories:
    - $HOME/.composer/cache

install: travis_retry composer install

script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --diff
  - vendor/bin/phpcs -s --config-set ignore_warnings_on_exit 1
  - vendor/bin/phpunit --testsuite unit --verbose

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email: false
