language: php

os:
  - linux
  - osx

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

cache:
  directories:
    - $HOME/.composer/cache

install: travis_retry composer install

script:
  - vendor/bin/phpunit --testsuite unit --verbose

notifications:
  email: false
